# This is a basic workflow to help you get started with Actions

name: Continuos Deployment ESHOP-REACT

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      # STEP BUILD REACT
      - name: Checkout Repo
        uses: actions/checkout@v2
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Build Project
        run: |
            npm install

      # STEP for COPY BUILD file project to NGINX
      # - name: Deploy ESHOP-REACT
      #   uses: nogsantos/scp-deploy@master
      #   with:
      #     src: ./build/*
      #     host: ${{secrets.SSH_HOST}}
      #     remote: "/var/www/html"
      #     port: ${{secrets.SSH_PORT}}
      #     username: ${{secrets.SSH_USER}}
      #     key: ${{secrets.SSH_KEY}}